### ISSUE TITLE
Fishing Book not Appear at General Store

### ISSUE THREAD

**Issue by WavingCoconut** [guilherme-gm/KirieZ_DoraemonSoSMods#8]
I already copy the Fishbook folder into my game's BepInEx/plugins/ folder. But i not found it at general store, so i can't use this feature. I use Fishbook v1.1.0 and BepInEx_x64_5.4.21.0

![Screenshot 2023-07-16 110933](https://github.com/guilherme-gm/KirieZ_DoraemonSoSMods/assets/139667993/5b77765a-dc1d-4072-bd11-68ce08b81727)

**Comment by guilherme-gm** [comment]
Thanks for the report, I will try to check it soon

**Comment by guilherme-gm** [comment]
@WavingCoconut hi, I have fixed the issue with today's release: https://github.com/guilherme-gm/KirieZ_DoraemonSoSMods/releases/tag/v2023.07.23

You will need to update both Fishbook and kzModUtils to fix it.

Let me know if you run into any other issues. Thank you!

**Comment by WavingCoconut** [comment]
Great, thank you so much, i will try it again

**Comment by WavingCoconut** [comment]
I already update both Fishbook and kzModUtils, my position now is on year 1
winter day 10. But it still not work. I have try check general store daily
but the fish book still not appear. I already restart my steam and computer
too .
[image: Screenshot 2023-07-25 090032.jpg][image: 20230725083220_1.jpg]

**Comment by guilherme-gm** [comment]
Sorry for the delay. Looks like I broke something else 🤦‍♂️ I will check and update soon

**Comment by guilherme-gm** [comment]
@WavingCoconut I just released fishbook v1.1.2 which should now fix it. I tested in a new game save and I can see the item in there.

You can find it here: https://github.com/guilherme-gm/KirieZ_DoraemonSoSMods/releases/tag/v2023.07.29 or in Nexus

Sorry for the issues

**Comment by WavingCoconut** [comment]
Alright, thank you
